language: node_js

node_js:
  - 11
  - 10

os:
  - linux
  - osx

jobs:
  include:
    - stage: npm release
      node_js: 10
      deploy:
        provider: npm
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true
